version: "3.8"

services:
  myhouse24-db:
    image: mysql
    container_name: myhouse24-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myhouse24
      - MYSQL_PASSWORD=user
      - MYSQL_USER=user
    restart: always
  myhouse24-admin:
    build: .
    container_name: myhouse24-admin
    volumes:
      - file-volume:/files
    depends_on:
      - myhouse24-db
    ports:
      - target: 8080
        published: 8080
    environment:
      - myhouse24-db
    restart: always
  myhouse24-cabinet:
    build: C:/Users/Amir Banov/IdeaProjects/MyHouse24-User
    container_name: myhouse24-cabinet
    volumes:
      - file-volume:/files
    depends_on:
      - myhouse24-db
    ports:
      - target: 8082
        published: 8082
    environment:
      - myhouse24-db
    restart: always
  myhouse24-rest:
    build: C:/Users/Amir Banov/IdeaProjects/MyHouse24-Rest
    container_name: myhouse24-rest
    volumes:
      - file-volume:/files
    depends_on:
      - myhouse24-db
    ports:
      - target: 8083
        published: 8083
    environment:
      - myhouse24-db
    restart: always
  myhouse24-site:
    image: li4nost/my-house-24:site
    container_name: myhouse24-site
    volumes:
      - file-volume:/files
    depends_on:
      - myhouse24-db
    ports:
      - target: 8081
        published: 8081
    environment:
      - myhouse24-db
    restart: always
volumes:
  file-volume:




